### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by satoer** [TimPaterson/Fusion360-Batch-Post#17]
I made a simple bore path and when I try the script with the option "use individual operations" to check the "Restore rapid moves" (thats the reason I want to use this script) I got the following error:

> 0 files were written. 1 Setups were skipped due to error:
Failed on setup Setup6: Fusion 360 reported an exception Traceback (most recent call last):
  File "C:/Users/Michel/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/PostProcessAll.py", line 973, in PostProcessSetup
    match = regBody.match(line).groupdict();
AttributeError: 'NoneType' object has no attribute 'groupdict'

![afbeelding](https://user-images.githubusercontent.com/15175433/120100531-83035200-c141-11eb-8d19-8908e0a52116.png)
Any idea what went wrong?

**Comment by martinhansdk** [comment]
I'm seeing the same issue on a fresh install of the add-in.

**Comment by TimPaterson** [comment]
What post processor are you using?

**Comment by martinhansdk** [comment]
I'm using the GRBL post from https://github.com/martindb/mpcnc_posts_processor.

**Comment by TimPaterson** [comment]
That post is incompatible with PostProcessAll (when using "individual operations") because it does not write the tool number G-code ("Txx") to the file. The GRBL post that comes with Fusion 360 works fine.

I did find the code in DIYCNC_Common.js which suppresses writing the tool change on line 421. You can edit this line to change this, leaving it as: 
`if (properties.toolChangeEnabled) {`

Once this change was made, the post outputs the tool number and works with an updated PostProcessAll. There was a bug in PostProcessall that did like an M-code on the line before the tool change, and that has been fixed. It also now reports the specific error if the tool change is not present.

**Comment by satoer** [comment]
I'm using this post processor for the Onefinity cnc:
https://cam.autodesk.com/posts/post.php?name=onefinity
Is there something I should change also?

**Comment by TimPaterson** [comment]
Looking at the Onefinity post I see a small block of code starting at line 561 that makes the tool command a comment if it's the first section.  It looks like this:
```
    if (!isFirstSection()) {
      writeBlock("T" + toolFormat.format(tool.number), conditional(getProperty("useM06"), mFormat.format(6)));
    } else {
      writeComment("T" + toolFormat.format(tool.number));
    }
```
Just delete all lines of this block except the second one, leaving:
```
    writeBlock("T" + toolFormat.format(tool.number), conditional(getProperty("useM06"), mFormat.format(6)));
```

**Comment by satoer** [comment]
That seems to do the trick. Don't know if the rapids are actually restored (have not tried the GCode yet) But it finished the script without errors.

Thanks Tim.
